#TODO: Year and month pages
#TODO: Japanese content?
baseURL = "https://msrc-blog.microsoft.com/"
languageCode = "en-us"
title = "Microsoft Security Response Center"
DefaultContentLanguage = "en"

theme = "microsoft"
summaryLength = 10
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.


archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = true
buildExpired = false
canonifyURLs = false

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
  name = "MSRC"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "The Microsoft Security Response Center is part of the defender community and on the front line of security response evolution. For over twenty years, we have been engaged with security researchers working to protect customers and the broader ecosystem."


  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  toc = true
  showRelated = true
  hasTranslations = false
  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "Blog"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"


  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/duncanma"

  [[params.social]]
    name = "email"
    url  = "mailto:duncanma@duncanmackenzie.net"

  [[params.social]]
    name = "github"
    url  = "https://github.com/DuncanmaMSFT"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/duncanmackenzie/"

[languages]
  [languages.en]
    subtitle  = ""
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'


[related]

threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

[permalinks]
  Blog = '/:year/:month/:day/:title/'
  categories = "/blog/categories/:slug/"
  tags = "/blog/tags/:slug/"
